version: "3"
services:
    hub:
        image: selenium/hub:3.141.59
        ports:
            - "4444:4444"

    chrome_1:
        image: selenium/node-chrome:3.141.59-20200525
        volumes:
            #- /dev/shm:/dev/shm
            - ./jitsi-meet-torture/resources:/usr/share/jitsi-meet-torture/resources
        depends_on:
            - hub
        environment:
            #HUB_HOST: hub
            #REMOTE_HOST: http://localhost:5555
            - HUB_HOST=hub
            - HUB_PORT=4444
            - NODE_MAX_INSTANCES=10
            - NODE_MAX_SESSION=10

    chrome_2:
        image: selenium/node-chrome:3.141.59-20200525
        volumes:
            #- /dev/shm:/dev/shm
            - ./jitsi-meet-torture/resources:/usr/share/jitsi-meet-torture/resources
        depends_on:
            - hub
        environment:
            - HUB_HOST=hub
            - HUB_PORT=4444
            - NODE_MAX_INSTANCES=10
            - NODE_MAX_SESSION=10